name: Deploy to S3

on:
  push:
    branches: [ gh-pages ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: List files before sync
      run: |
        ls -la dist/
        echo "Syncing to S3 bucket: ${{ secrets.AWS_S3_BUCKET }}"
        echo "AWS Region: ${{ secrets.AWS_REGION }}"

    - name: Deploy to S3
      run: |
        aws s3 sync ./dist/ s3://${{ secrets.AWS_S3_BUCKET }} \
          --delete \
          --acl public-read \
          --cache-control "max-age=31536000,public"
        
        echo "Sync completed. Verifying files in S3..."
        aws s3 ls s3://${{ secrets.AWS_S3_BUCKET }} --recursive --human-readable --summarize
        
        # Invalidate CloudFront cache if you're using CloudFront
        # aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
